/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Faction = IDL.Variant({
  'vikings' : IDL.Null,
  'mongols' : IDL.Null,
  'romans' : IDL.Null,
});
export const FactionStats = IDL.Record({
  'totalMatches' : IDL.Nat,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'faction' : Faction,
});
export const MatchStats = IDL.Record({
  'totalMatches' : IDL.Nat,
  'byFaction' : IDL.Vec(FactionStats),
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'totalDurationSeconds' : IDL.Nat,
});
export const AiDifficulty = IDL.Variant({
  'normal' : IDL.Null,
  'easy' : IDL.Null,
  'hard' : IDL.Null,
});
export const MapSize = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const PlayerSettings = IDL.Record({
  'preferredFaction' : Faction,
  'preferredDifficulty' : AiDifficulty,
  'lastMapSize' : MapSize,
});
export const MatchId = IDL.Nat;
export const MatchResult = IDL.Variant({
  'defeat' : IDL.Null,
  'victory' : IDL.Null,
});
export const Timestamp = IDL.Nat;
export const MatchRecord = IDL.Record({
  'id' : MatchId,
  'result' : MatchResult,
  'mapSize' : MapSize,
  'difficulty' : AiDifficulty,
  'recordedAt' : Timestamp,
  'durationSeconds' : IDL.Nat,
  'faction' : Faction,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatchStats' : IDL.Func([], [MatchStats], ['query']),
  'getSettings' : IDL.Func([], [IDL.Opt(PlayerSettings)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listRecentMatches' : IDL.Func([IDL.Nat], [IDL.Vec(MatchRecord)], ['query']),
  'recordMatch' : IDL.Func(
      [Faction, MapSize, AiDifficulty, MatchResult, IDL.Nat],
      [MatchId],
      [],
    ),
  'saveSettings' : IDL.Func([PlayerSettings], [PlayerSettings], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Faction = IDL.Variant({
    'vikings' : IDL.Null,
    'mongols' : IDL.Null,
    'romans' : IDL.Null,
  });
  const FactionStats = IDL.Record({
    'totalMatches' : IDL.Nat,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'faction' : Faction,
  });
  const MatchStats = IDL.Record({
    'totalMatches' : IDL.Nat,
    'byFaction' : IDL.Vec(FactionStats),
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'totalDurationSeconds' : IDL.Nat,
  });
  const AiDifficulty = IDL.Variant({
    'normal' : IDL.Null,
    'easy' : IDL.Null,
    'hard' : IDL.Null,
  });
  const MapSize = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const PlayerSettings = IDL.Record({
    'preferredFaction' : Faction,
    'preferredDifficulty' : AiDifficulty,
    'lastMapSize' : MapSize,
  });
  const MatchId = IDL.Nat;
  const MatchResult = IDL.Variant({
    'defeat' : IDL.Null,
    'victory' : IDL.Null,
  });
  const Timestamp = IDL.Nat;
  const MatchRecord = IDL.Record({
    'id' : MatchId,
    'result' : MatchResult,
    'mapSize' : MapSize,
    'difficulty' : AiDifficulty,
    'recordedAt' : Timestamp,
    'durationSeconds' : IDL.Nat,
    'faction' : Faction,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatchStats' : IDL.Func([], [MatchStats], ['query']),
    'getSettings' : IDL.Func([], [IDL.Opt(PlayerSettings)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listRecentMatches' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MatchRecord)],
        ['query'],
      ),
    'recordMatch' : IDL.Func(
        [Faction, MapSize, AiDifficulty, MatchResult, IDL.Nat],
        [MatchId],
        [],
      ),
    'saveSettings' : IDL.Func([PlayerSettings], [PlayerSettings], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };